version: '3.8'

services:
  app:
    build: .
    container_name: siguiendolaspatitas-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    env_file:
      - .env.development
    working_dir: /usr/src/app/src

  db:
    image: mysql:8.0
    container_name: siguiendolaspatitas-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: siguiendolaspatitas
    volumes:
      - db_data:/var/lib/mysql
      - ./database/siguiendolaspatitas.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
